---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: devops-poc
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/renatovassao/devops-poc
